# Generated by Django 5.2.3 on 2025-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
