# Generated by Django 5.2.3 on 2025-06-24 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_department_alter_semester_number_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.department'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='cgpa',
            field=models.FloatField(),
        ),
    ]
