# Generated by Django 5.2.3 on 2025-06-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_userresult_department_alter_userresult_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='calculator.department'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.department'),
        ),
    ]
