# Generated by Django 5.2.3 on 2025-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_subject_department_alter_userresult_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresult',
            name='total_grade_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='cgpa',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
