# Generated by Django 5.2.3 on 2025-06-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_userresult_total_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.department'),
        ),
    ]
